title: "<span style='font-size: 12px; color: green;'>Hello World!</span>"
logo: "photo3.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <strong>Fatemeh Ghofrani</strong>  
 <br><br>
 <span style="font-size: 12px; color: green; font-family: 'Arial', sans-serif;">
  A machine learning
  <br><br>
  <span style="font-size: 12px; color: green; font-family: 'Arial', sans-serif;">
  enthusiast and researcher
 </span>
<head>
  <!-- Include Font Awesome stylesheet -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha384-HjQCgfX2HrNnEh3zjGqGeNDG1yA7H7B6zfiNdFvaUIC32McrJks8usQJ+0mwq6+1" crossorigin="anonymous">
</head>

<body>
  <span style="color: #3498db; font-family: 'Arial', sans-serif;">
    A machine learning enthusiast and researcher. Connect with me on:
    <br><br>
    <i class="fas fa-linkedin" style="color: #3498db;"></i>
    <a href="http://www.linkedin.com/in/your-linkedin" style="color: #3498db; text-decoration: none;">LinkedIn</a> |
    <i class="fas fa-graduation-cap" style="color: #3498db;"></i>
    <a href="https://scholar.google.com/citations?user=your-scholar-id" style="color: #3498db; text-decoration: none;">Google Scholar</a> |
    <i class="fab fa-github" style="color: #3498db;"></i>
    <a href="https://github.com/your-github-username" style="color: #3498db; text-decoration: none;">GitHub</a> |
    <i class="far fa-envelope" style="color: #3498db;"></i>
    <a href="mailto:your@email.com" style="color: #3498db; text-decoration: none;">Email</a>
  </span>
</body>

  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
