name: Fatemeh Ghofrani
avatar: /path/to/your/profile-photo.jpg

links:
  - title: "Google Scholar"
    url: "https://scholar.google.com/citations?user=NWOeb_AAAAAJ&hl=en&oi=ao"
  - title: "Email"
    url: "mailto:ghofrani@email.sc.edu"
  - title: "GitHub"
    url: "https://github.com/gh-fatima"
  - title: "LinkedIn"
    url: "http://www.linkedin.com/in/fatemeh-ghofrani-a0331b7a/"



