title: "<span style='font-size: 14px; color: green;'>Hi there!</span>"
logo: "photo3.png" # your photo (or logo) here
description: |
  <strong>Fatemeh Ghofrani</strong>  
  <br>
  <span style="font-size: 10px; color: green; font-family: 'Arial', sans-serif;">
    A machine learning researcher
  </span>
links:
  - title: "LinkedIn"
    url: "http://www.linkedin.com/in/your-linkedin"
  - title: "Google Scholar"
    url: "https://scholar.google.com/citations?user=your-scholar-id"
  - title: "GitHub"
    url: "https://github.com/your-github-username"
  - title: "Email"
    url: "mailto:your@email.com"



  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
