
theme: jekyll-theme-minimal
title: Fatemeh Ghofrani
links:
  - [Google Scholar](https://scholar.google.com/citations?user=NWOeb_AAAAAJ&hl=en&oi=ao)
  - [Email](mailto:ghofrani@email.sc.edu)
  - [GitHub](https://github.com/gh-fatima)
  - [LinkedIn](http://www.linkedin.com/in/fatemeh-ghofrani-a0331b7a/)

